name: .NET Build & Test

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore PopulationReport/PopulationReport.sln

      - name: Build project
        run: dotnet build PopulationReport/PopulationReport.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test PopulationReport/PopulationReport.sln --no-build --verbosity normal
